# Generated by Django 3.0.8 on 2020-09-19 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price_nett', models.FloatField(default=0)),
                ('price_gross', models.FloatField(default=0)),
                ('tax_rate', models.FloatField(default=0)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('prod_total_nett', models.FloatField(default=0)),
                ('prod_total_tax', models.FloatField(default=0)),
                ('prod_total_gross', models.FloatField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice')),
            ],
        ),
    ]
