# Generated by Django 3.0.8 on 2020-07-26 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice'),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_total_gross',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_total_nett',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_total_tax',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ProductInvoice',
        ),
    ]
