# Generated by Django 3.0.8 on 2020-09-19 07:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=100)),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('city_created', models.CharField(max_length=100)),
                ('total_nett', models.FloatField(default=0.0)),
                ('total_tax', models.FloatField(default=0.0)),
                ('total_gross', models.FloatField(default=0.0)),
                ('bank_num_account', models.CharField(max_length=100)),
                ('date_supply', models.DateField(default=django.utils.timezone.now)),
                ('date_due', models.DateField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buyer', to='contractors.Contractor')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='contractors.Contractor')),
            ],
        ),
    ]
