# Generated by Django 3.0.8 on 2020-07-22 18:31

import datetime

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('contractors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(default=datetime.date.today)),
                ('city_created', models.CharField(max_length=100)),
                ('total_nett', models.FloatField(default=0.0)),
                ('total_tax', models.FloatField(default=0.0)),
                ('total_gross', models.FloatField(default=0.0)),
                ('bank_num_account', models.CharField(max_length=100)),
                ('date_supply', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_due', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('buyer',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buyer',
                                   to='contractors.Contractor')),
                ('seller',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller',
                                   to='contractors.Contractor')),
            ],
        ),
    ]
