# Generated by Django 3.0.8 on 2020-08-16 22:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20200816_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_due',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_supply',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
