# Generated by Django 3.0.8 on 2020-09-19 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(default='UNDEFINED', max_length=100)),
                ('city', models.CharField(default='UNDEFINED', max_length=100)),
                ('zip_code', models.CharField(default='UNDEFINED', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='UNDEFINED', max_length=100)),
                ('tin', models.CharField(default='UNDEFINED', max_length=100)),
                ('bank_name', models.CharField(default='UNDEFINED', max_length=100)),
                ('bank_account_num', models.CharField(default='UNDEFINED', max_length=26)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
