# Generated by Django 3.0.8 on 2020-09-19 07:48

from django.db import migrations
from mybusiness.factories import initial_data_creator

creator = initial_data_creator.Creator()


def load_data(apps, schema_editor):
    creator.create_data()


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
